using System;
using System.Numerics;
using Flame.Constants;

namespace UnitTests
{
    /// <summary>
    /// A collection of helpers that make it easier to randomly generate values.
    /// </summary>
    public static class FuzzHelpers
    {
        /// <summary>
        /// Generates a random integer constant.
        /// </summary>
        /// <param name="random">A random number generator.</param>
        /// <returns>An integer constant that conforms to its spec.</returns>
        public static IntegerConstant NextIntegerConstant(this Random random)
        {
            return random.NextIntegerConstant(random.NextIntegerSpec());
        }

        /// <summary>
        /// Generates a random integer constant that conforms to a particular spec.
        /// </summary>
        /// <param name="random">A random number generator.</param>
        /// <param name="spec">The spec for the integer constant to generate.</param>
        /// <returns>An integer constant that conforms to its spec.</returns>
        public static IntegerConstant NextIntegerConstant(this Random random, IntegerSpec spec)
        {
            var bigNum = BigInteger.Zero;
            for (int i = 0; i < spec.Size / 30; i++)
            {
                bigNum = (bigNum << 30) | random.Next(0, 1 << 30);
            }
            bigNum = (bigNum << (spec.Size % 30)) | random.Next(0, 1 << (spec.Size % 30));
            return new IntegerConstant(bigNum, spec).Normalized;
        }

        /// <summary>
        /// Generates a random integer spec.
        /// </summary>
        /// <param name="random">A random number generator.</param>
        /// <returns>An integer spec.</returns>
        public static IntegerSpec NextIntegerSpec(this Random random)
        {
            return random.NextIntegerSpec(4097);
        }

        /// <summary>
        /// Generates a random integer spec.
        /// </summary>
        /// <param name="random">A random number generator.</param>
        /// <param name="maxSize">
        /// The size of the largest integer spec that can be generated by this function.
        /// </param>
        /// <returns>An integer spec.</returns>
        public static IntegerSpec NextIntegerSpec(this Random random, int maxSize)
        {
            return new IntegerSpec(random.Next(1, maxSize), random.NextBoolean());
        }

        /// <summary>
        /// Generates a random Boolean.
        /// </summary>
        /// <param name="random">A random number generator.</param>
        /// <returns>A Boolean value.</returns>
        public static bool NextBoolean(this Random random)
        {
            return random.Next(0, 2) == 0;
        }

        /// <summary>
        /// Generates an array of random elements.
        /// </summary>
        /// <param name="random">A random number generator.</param>
        /// <param name="length">The length of the array to generate.</param>
        /// <param name="nextElement">Generates a random element.</param>
        /// <typeparam name="T">The type of element to generate.</typeparam>
        /// <returns>An array of randomly generated elements.</returns>
        public static T[] NextArray<T>(
            this Random random,
            int length,
            Func<Random, T> nextElement)
        {
            var arr = new T[length];
            for (int i = 0; i < length; i++)
            {
                arr[i] = nextElement(random);
            }
            return arr;
        }

        /// <summary>
        /// Generates a random ASCII string.
        /// </summary>
        /// <param name="random">A random number generator.</param>
        /// <param name="length">The length of the string.</param>
        /// <returns>An ASCII character string.</returns>
        public static string NextAsciiString(this Random random, int length)
        {
            return new string(
                random.NextArray(
                    length,
                    rng =>
                    {
                        switch (rng.Next(0, 3))
                        {
                            case 0:
                                return (char)rng.Next('0', '9' + 1);
                            case 1:
                                return (char)rng.Next('a', 'z' + 1);
                            case 2:
                            default:
                                return (char)rng.Next('A', 'Z' + 1);
                        }
                    }));
        }
    }
}
